# -*- coding: utf-8 -*-
"""Clase_Pandas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wOoFvlSDB5Yqq2OSsr2RSAmV5qoD3SlB
"""

# import numpy as np
# import pandas as pd
# # Una Series viene siendo como una lista, siempre debe escribirse la S en mayúscula
# fruteria = pd.Series(["Pera", "Mango", "Fresa", "Papaya"])
# print(fruteria)
# fruteria1 = pd.Series(["Pera", "Mango", "Fresa", "Papaya"], index=[90,8,60,0])
# print(fruteria1)
# print("\n")
# print("-----------------------------------------------------------------------------------")


# import numpy as np
# import pandas as pd
# # Una Series viene siendo como una lista, siempre debe escribirse la S en mayúscula
# fruteria = pd.Series(["Pera", "Mango", "Fresa", "Papaya"])
# print(fruteria[1])
# fruteria1 = pd.Series(["Pera", "Mango", "Fresa", "Papaya"], index=[90,8,60,0])
# print(fruteria1[60])

# fruteria2 = pd.DataFrame({"frutas":["Pera", "Mango", "Fresa", "Papaya"], "precio":[1000,2000,3000,4000]})

# print(fruteria2)

# print("\n")
# print("-----------------------------------------------------------------------------------")

# import numpy as np
# import pandas as pd
# # Una Series viene siendo como una lista, siempre debe escribirse la S en mayúscula
# fruteria = pd.Series(["Pera", "Mango", "Fresa", "Papaya"])
# print(fruteria[1])
# fruteria1 = pd.Series(["Pera", "Mango", "Fresa", "Papaya"], index=[90,8,60,0])
# print(fruteria1[60])

# fruteria2 = pd.DataFrame({"frutas":["Pera", "Mango", "Fresa", "Papaya"], "precio":[1000,2000,3000,4000]})
# # loc, me permite insertar un nuevo elemento
# fruteria2.loc[5]=["Banano", 5000]

# print(fruteria2)

# print("\n")
# print("-----------------------------------------------------------------------------------")

# import numpy as np
# import pandas as pd
# # Una Series viene siendo como una lista, siempre debe escribirse la S en mayúscula
# fruteria = pd.Series(["Pera", "Mango", "Fresa", "Papaya"])
# print(fruteria[1])
# fruteria1 = pd.Series(["Pera", "Mango", "Fresa", "Papaya"], index=[90,8,60,0])
# print(fruteria1[60])

# fruteria2 = pd.DataFrame({"frutas":["Pera", "Mango", "Fresa", "Papaya"], "precio":[1000,2000,3000,4000]})
# # loc, me permite insertar un nuevo elemento
# fruteria2.loc[5]=["Banano", 5000]
# fruteria2.loc[3]=["Banano", 5000]
# print(fruteria2)

# print("\n")
# print("-----------------------------------------------------------------------------------")


# import numpy as np
# import pandas as pd
# # Una Series viene siendo como una lista, siempre debe escribirse la S en mayúscula
# fruteria = pd.Series(["Pera", "Mango", "Fresa", "Papaya"])
# print(fruteria[1])
# fruteria1 = pd.Series(["Pera", "Mango", "Fresa", "Papaya"], index=[90,8,60,0])
# print(fruteria1[60])

# fruteria2 = pd.DataFrame({"frutas":["Pera", "Mango", "Fresa", "Papaya"], "precio":[1000,2000,3000,4000]})

# posicion=int(input("Ingrese la posición: "))
# fruta=input("Ingrese la fruta: ")
# precio=int(input("Ingrese el precio :"))

# fruteria2.loc[posicion]=[fruta,precio]

# print(fruteria2)

# print("\n")
# print("-----------------------------------------------------------------------------------")

import Numpy as np
import Pandas as pd
# Una Series viene siendo como una lista, siempre debe escribirse la S en mayúscula
fruteria = pd.Series(["Pera", "Mango", "Fresa", "Papaya"])
print(fruteria[1])
fruteria1 = pd.Series(["Pera", "Mango", "Fresa", "Papaya"], index=[90,8,60,0])
print(fruteria1[60])

fruteria2 = pd.DataFrame({"frutas":["Pera", "Mango", "Fresa", "Papaya"], "precio":[1000,2000,3000,4000]})

columna=input("Ingrese la columna: ")
fruteria2[columna]=pd.Series([6, "", 45, 3])
columna1=input("Ingrese la columna: ")
fruteria2[columna1]=pd.Series([1.5,3.5,7.8,6.3])

posicion=int(input("Ingrese la posición: "))
fruta=input("Ingrese la fruta: ")
precio=int(input("Ingrese el precio :"))
cantidad=int(input("Ingrese la cantidad: "))
peso=input("Ingrese el peso: ")
# En que indice va ese objeto
fruteria2.loc[posicion]=[fruta,precio,cantidad,peso]

print(fruteria2)

print("\n")
print("-----------------------------------------------------------------------------------")